const CHAKRAS = {
   root: {
        "name": "Root",
        "sanskrit": "Muladhara",
        "location": "base of spine and perineum",
        "color": "red",
        "blocked": "fearful, anxious, unsure, financial instability, ungrounded",
        "overactive": "greedy, lethargic, aggressive, cynical, materialistic",
        "balanced":  "safe, secure, grounded, happy to be alive",
        "image": "rootImg.jpeg",
        "crystal": "ruby, bloodstone, hematite",
        "essentialOil": "patchouli, rosewood, juniper",
        "mantra": [ "I am"],
        "natureTherapy": "gardening, hiking, earth sitting",
        "yoga": "https://www.youtube.com/embed/r9PmDj8BKeg",
        "meditation": "https://www.youtube.com/embed/cdScjlpftMM"
    },
   sacral: {
        "name": "Sacral",
        "sanskrit": "Svadhisthana",
        "location": "2-3 inches below the navel, reproductive organs, and spleen",
        "color": "orange",
        "blocked": "low libido, fear of intimacy, no creativity, isolated",
        "overactive": "over-emotional, fixated on sex, hedonistic, manipulative",
        "balanced":  "passion, creative, healthy libido, optimistic, open",
        "image": "",
        "crystal": "coral, fire opal, carnelian, garnet",
        "essentialOil": "ylang ylang, jasmine, orange", 
        "mantra": [ "I feel"],
        "natureTherapy": "spend time by or in water, creative expression, sexual expression",
        "yoga": "https://www.youtube.com/embed/hsy_t2u3zjU",
        "meditation": "https://www.youtube.com/embed/QcId1qEKGJo"
    },
   solar: {
        "name": "Solar",
        "sanskrit": "Manipura",
        "location": "below the chest, solar plexus, above the navel",
        "color": "yellow",
        "blocked": "low self-esteem, feeling powerless, inferior",
        "overactive": "power hungry, domineering, perfectionist, critical",
        "balanced":  "confident, in control, good self-image, ambitious",
        "image": "",
        "crystal": "tiger eye, citrine, amber",
        "essentialOil": "lemon, peppermint, ginger, neroli", 
        "mantra": [ "I do"],
        "natureTherapy": "sunbathing practice healthy boundaries",
        "yoga": "https://www.youtube.com/embed/N4mfzXcXseY",
        "meditation": "https://www.youtube.com/embed/5wHFfouqivU"
    },
   heart: {
        "name": "Heart",
        "sanskrit": "Anahata",
        "location": "center of chest and heart",
        "color": "green",
        "blocked": "lack of empathy, bitter, hateful, trust issues, intolerant",
        "overactive": "jealous, codependent, self-sacrificing, give too much of yourself",
        "balanced":  "peaceful, loving, compassionate, tolerant, warm, open",
        "image": "",
        "crystal": "emerald, jade, aventurine, rose quartz",
        "essentialOil": "chamomile, bergamot, lemongrass", 
        "mantra": [ "I love"],
        "natureTherapy": "time to yourself, self-care",
        "yoga": "https://www.youtube.com/embed/eCp5jYAZik4",
        "meditation": "https://www.youtube.com/embed/5Yfeo3kPVSs"
    }, 
   throat: {
        "name": "Throat",
        "sanskrit": "Vishuddha",
        "location": "throat",
        "color": "blue",
        "blocked": "can't express or speak out, misunderstood, secretive, not a good listener",
        "overactive": "opinionated, loud, critical, gossipy, talk over others, harsh words",
        "balanced":  "confident expression, clear communicator, creative, diplomatic",
        "image": "",
        "crystal": "sodalite, sapphire, turquoise",
        "essentialOil": "sage, peppermint", 
        "mantra": [ "I speak"],
        "natureTherapy": "singing, chanting, meaningful discussions",
        "yoga": "https://www.youtube.com/embed/uOIKfO77zM4",
        "meditation": "https://www.youtube.com/embed/gMJ346GHatM"
    },
   thirdEye: {
        "name": "Third Eye",
        "sanskrit": "Anja",
        "location": "center of forehead above eyebrows",
        "color": "indigo",
        "blocked": "poor judgement, lack focus, poor imagination, can't see beyond the physical ",
        "overactive": "nightmares, delusions, hallucinations, obsessive",
        "balanced":  "imaginative, intuitive, clear thoughts and vision, sees beyond physical",
        "image": "",
        "crystal": "amethyst, fluorite, lapis lazuli",
        "essentialOil": "lavender, pine, sage, sandalwood",
        "mantra": [ "I see"],
        "natureTherapy": "dreaming of possibilities, releasing preconceived notions",
        "yoga": "https://www.youtube.com/embed/XMQGC7eh1sI",
        "meditation": "https://www.youtube.com/embed/kBhHUxLcSPM"
    },
   crown: {
        "name": "Crown",
        "sanskrit": "Sahasrara",
        "location": "top of head",
        "color": "violet",
        "blocked": "depression, learning difficulties, weak faith, anger at the divine, brain fog",
        "overactive": "dogmatic, judgmental, spiritual addiction, ungrounded",
        "balanced":  "strong faith, universal love, intelligent, aware, wise, understanding",
        "image": "",
        "crystal": "amethyst, diamond, quartz crystal",
        "essentialOil": "frankincense, sandalwood, myrrh", 
        "mantra": [ "I understand"],
        "natureTherapy": "meditation, cloud watching, star gazing",
        "yoga": "https://www.youtube.com/embed/GyYLSktZh5E",
        "meditation": "https://www.youtube.com/embed/kJwC6AgHefY"
    }
}

export default CHAKRAS
