const CHAKRAS = {
   root: {
        "name": "Root",
        "sanskrit": "Muladhara",
        "location": "base of spine and perineum",
        "color": "red",
        "blocked": "fear, anxiety, indecision, financial instability, and unstable feelings",
        "overactive": "greed driven, lethargy, aggression, cynicism, and worldy impulses",
        "balanced":  "safe, secure, grounded, and happy to be alive",
        "crystal": "ruby, bloodstone, and hematite",
        "essentialOil": "patchouli, rosewood, and juniper",
        "mantra": [ "I am"],
        "natureTherapy": "gardening, hiking, and earth sitting",
        "yoga": "https://www.youtube.com/embed/r9PmDj8BKeg",
        "meditation": "https://www.youtube.com/embed/cdScjlpftMM"
    },
   sacral: {
        "name": "Sacral",
        "sanskrit": "Svadhisthana",
        "location": "2-3 inches below the navel, reproductive organs, and spleen",
        "color": "orange",
        "blocked": "low libido, fear of intimacy, no creativity, and isolation",
        "overactive": "over-emotional, a fixation on sex, hedonistic, and manipulative",
        "balanced":  "passion, creativity, a healthy libido, optimisim, and openness",
        "crystal": "coral, fire opal, carnelian, and garnet",
        "essentialOil": "ylang ylang, jasmine, and orange", 
        "mantra": [ "I feel"],
        "natureTherapy": "spend time by or in water, creative expression, and sexual expression",
        "yoga": "https://www.youtube.com/embed/hsy_t2u3zjU",
        "meditation": "https://www.youtube.com/embed/QcId1qEKGJo"
    },
   solar: {
        "name": "Solar",
        "sanskrit": "Manipura",
        "location": "below the chest, solar plexus, above the navel",
        "color": "yellow",
        "blocked": "low self-esteem, feeling powerless, and inferior",
        "overactive": "power hungry, domineering, perfectionist, and critical",
        "balanced":  "confident, in control, have a good self-image, and ambitious",
        "crystal": "tiger eye, citrine, and amber",
        "essentialOil": "lemon, peppermint, ginger, and neroli", 
        "mantra": [ "I do"],
        "natureTherapy": "sunbathing practice healthy and boundaries",
        "yoga": "https://www.youtube.com/embed/N4mfzXcXseY",
        "meditation": "https://www.youtube.com/embed/5wHFfouqivU"
    },
   heart: {
        "name": "Heart",
        "sanskrit": "Anahata",
        "location": "center of chest and heart",
        "color": "green",
        "blocked": "lack of empathy, bitter, hateful, trust issues, and intolerant",
        "overactive": "jealous, codependent, self-sacrificing, and give too much of yourself",
        "balanced":  "peaceful, loving, compassionate, tolerant, and warm, open",
        "crystal": "emerald, jade, aventurine, and rose quartz",
        "essentialOil": "chamomile, bergamot, and lemongrass", 
        "mantra": [ "I love"],
        "natureTherapy": "time to yourself, and self-care",
        "yoga": "https://www.youtube.com/embed/eCp5jYAZik4",
        "meditation": "https://www.youtube.com/embed/5Yfeo3kPVSs"
    }, 
   throat: {
        "name": "Throat",
        "sanskrit": "Vishuddha",
        "location": "throat",
        "color": "blue",
        "blocked": "trouble expressing yourself or speaking out, misunderstood, secretive, and impatience when listening",
        "overactive": "opinionated, loud, critical, gossipy, talk over others, and harsh words",
        "balanced":  "confident in expression, clear in communication, creative, and diplomatic",
        "crystal": "sodalite, sapphire, and turquoise",
        "essentialOil": "sage, and peppermint", 
        "mantra": [ "I speak"],
        "natureTherapy": "singing, chanting, and meaningful discussions",
        "yoga": "https://www.youtube.com/embed/uOIKfO77zM4",
        "meditation": "https://www.youtube.com/embed/gMJ346GHatM"
    },
   thirdEye: {
        "name": "Third Eye",
        "sanskrit": "Anja",
        "location": "center of forehead above eyebrows",
        "color": "indigo",
        "blocked": "poor judgement, lack of focus, poor imagination, and can't see beyond the physical ",
        "overactive": "nightmares, delusions, hallucinations, and obsessions",
        "balanced":  "imaginative, intuitive, clear thoughts and vision, and see beyond the physical",
        "crystal": "amethyst, fluorite, and lapis lazuli",
        "essentialOil": "lavender, pine, sage, and sandalwood",
        "mantra": [ "I see"],
        "natureTherapy": "dreaming of possibilities, and releasing preconceived notions",
        "yoga": "https://www.youtube.com/embed/XMQGC7eh1sI",
        "meditation": "https://www.youtube.com/embed/kBhHUxLcSPM"
    },
   crown: {
        "name": "Crown",
        "sanskrit": "Sahasrara",
        "location": "top of head",
        "color": "violet",
        "blocked": "depression, learning difficulties, weak faith, anger at the divine, and brain fog",
        "overactive": "dogmatic, judgmental, spiritual addiction, and ungrounded",
        "balanced":  "faith, universal love, intelligent, awareness, wisdom, and understanding",
        "crystal": "amethyst, diamond, and quartz crystal",
        "essentialOil": "frankincense, sandalwood, and myrrh", 
        "mantra": [ "I understand"],
        "natureTherapy": "meditation, cloud watching, and star gazing",
        "yoga": "https://www.youtube.com/embed/GyYLSktZh5E",
        "meditation": "https://www.youtube.com/embed/kJwC6AgHefY"
    }
}

export default CHAKRAS
